# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5420491e6b5dcdc2a6b1a51bdcea2a6d80062b958e4143e0210f6e8790ef244b78324cd7de7a712456ec13493125d461ac9143a69a49c3095b618960b79633ba

test:
  secret_key_base: bf18a636829ffe51f6b9c78dae7de6d8bb4bfedb195523bf229e54e9904d4403e3e38b8e7312983499b47b9e815e98846e08c68520aef051788d5204aff3a5f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
